### ISSUE TITLE
Неактуальный текст в строке поиска

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Oleh-Verhulenko/Fooding24-Android#3]
При переходе по карте к другому городу (от Братиславы к Скалице), цифры под строкой поиска актуальные, а текст в строке поиска — нет (относится к изначальному результату) - http://joxi.ru/LmGj1GysewRYzr.

**Comment by DmitriyTriakin** [comment]
Есть предложение написать что-то типа "All in focus on map", что скажешь?
Пока исправил на этот текст

**Comment by Oleh-Verhulenko** [comment]
Да, давай так.
