### ISSUE TITLE
Непонятное табло

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Oleh-Verhulenko/Fooding24-Android#4]
При попытке выбрать количество персон, появляется табло с цифрами. Сам выбор количества в этом случае работает довольно криво и неудобно - http://joxi.ru/Drlp4RzFvV4Zpr.

**Comment by DmitriyTriakin** [comment]
Исправил

**Comment by Oleh-Verhulenko** [comment]
Табло пропало, но оставшийся выбор количества персон не реагирует на нажатие - http://joxi.ru/82Qq6EeFjwgoL2. Я могу прокрутить карусель до нужной цифры, но не могу нажать.

**Comment by DmitriyTriakin** [comment]
Исправил
