### ISSUE TITLE
Шаг назад с экрана ресторана

### ISSUE THREAD

**Issue by Oleh-Verhulenko** [Oleh-Verhulenko/Fooding24-Android#7]
Переход со списка ресторанов в ресторан. При нажатии кнопки "Назад" — попадаем на самый первый, главный экран. Ожидался переход к списку ресторанов.

**Comment by DmitriyTriakin** [comment]
Исправил

**Comment by Oleh-Verhulenko** [comment]
Не исправлено

**Comment by DmitriyTriakin** [comment]
Понял, исправил
